README.md
bin/sport-ngin-aws-auditor
lib/sport_ngin_aws_auditor/aws.rb
lib/sport_ngin_aws_auditor/commands/audit.rb
lib/sport_ngin_aws_auditor/commands/export.rb
lib/sport_ngin_aws_auditor/commands/inspect.rb
lib/sport_ngin_aws_auditor/convenience_wrappers.rb
lib/sport_ngin_aws_auditor/scripts/audit.rb
lib/sport_ngin_aws_auditor/scripts/export.rb
lib/sport_ngin_aws_auditor/scripts/inspect.rb
spec/sport_ngin_aws_auditor/aws_spec.rb

Provides an option for authentication through AWS roles instead of through an ~/.aws/credentials file through a new flag `:with_roles`.
Deploy Plan
-----------
Rollback Plan
-------------
URLs
----
QA Plan
-------

Authentication with AWS roles instead of credentials file

---

lib/sport_ngin_aws_auditor/cache_instance.rb
lib/sport_ngin_aws_auditor/ec2_instance.rb
lib/sport_ngin_aws_auditor/rds_instance.rb
lib/sport_ngin_aws_auditor/scripts/audit.rb
spec/sport_ngin_aws_auditor/cache_instance_spec.rb
spec/sport_ngin_aws_auditor/ec2_instance_spec.rb
spec/sport_ngin_aws_auditor/rds_instance_spec.rb

The logic for recognizing Windows/Linux/VPC instances was wrong previously. Now the logic should be fixed to more accurately represent the platform of each instance. Previously, all instances came out as saying VPC, but we want to also be specific about whether it is Windows or Linux, so now it will read out `Linux VPC` or `Windows VPC`.
Deploy Plan
-----------
* checkout master
* `op accept-pull`
* `soyuz deploy` and push new version to RubyGems
Rollback Plan
-------------
URLs
----
QA Plan
-------

Proper recognition of windows/linux/vpc instances

---

lib/sport_ngin_aws_auditor/scripts/audit.rb

When printing to Slack, don't say there are discrepancies if there are only instances that have tags.
Deploy Plan
-----------
Rollback Plan
-------------
URLs
----
QA Plan
-------

Fixing bug where Slack will print discrepancies if there are *only* tagged instances

---

lib/sport_ngin_aws_auditor/cache_instance.rb
lib/sport_ngin_aws_auditor/ec2_instance.rb
lib/sport_ngin_aws_auditor/rds_instance.rb
spec/sport_ngin_aws_auditor/cache_instance_spec.rb
spec/sport_ngin_aws_auditor/ec2_instance_spec.rb
spec/sport_ngin_aws_auditor/rds_instance_spec.rb

Also fixes an issue where rds reservations containing more than 1 reserved db instance would only be counted as a single reserved instance.
I was able to find the listings of available product_descriptions using this:
```
marker = nil
reserved_db_product_descriptions = []
loop do
resp = rds_client.describe_reserved_db_instances_offerings({marker: marker})
marker = resp.marker
reserved_db_product_descriptions += resp.reserved_db_instances_offerings.map(&:product_description)
break if marker.nil?
end
reserved_db_product_descriptions.uniq
=> ["sqlserver-ee(li)", "sqlserver-se(li)", "oracle-se(byol)", "mariadb", "sqlserver-ee(byol)", "oracle-se1(li)", "oracle-se2 (byol)", "sqlserver-se(byol)", "aurora", "sqlserver-web(li)", "postgresql", "oracle-ee(byol)", "mysql", "oracle-se1(byol)", …
```

Add other RDS engine types

---

lib/sport_ngin_aws_auditor/cache_instance.rb
lib/sport_ngin_aws_auditor/ec2_instance.rb
lib/sport_ngin_aws_auditor/instance_helper.rb
lib/sport_ngin_aws_auditor/rds_instance.rb
lib/sport_ngin_aws_auditor/scripts/audit.rb
spec/sport_ngin_aws_auditor/cache_instance_spec.rb
spec/sport_ngin_aws_auditor/ec2_instance_spec.rb
spec/sport_ngin_aws_auditor/rds_instance_spec.rb

Print the expiration date of recently retired reserved instances to help users complete their audits.
Deploy Plan
-----------
* checkout master
* `op accept-pull 16`
Rollback Plan
-------------
URLs
----
http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html
QA Plan
-------

Print reserved instances that have retired in past week

---

lib/sport_ngin_aws_auditor/audit_data.rb
lib/sport_ngin_aws_auditor/instance_helper.rb
lib/sport_ngin_aws_auditor/recently_retired_tag.rb
lib/sport_ngin_aws_auditor/scripts/audit.rb
spec/sport_ngin_aws_auditor/audit_data_spec.rb
spec/sport_ngin_aws_auditor/recently_retired_tag_spec.rb

Print the tags of instances that have expired between the past week and today.
Deploy Plan
-----------
* checkout master
* `op accept-pull 17`
Rollback Plan
-------------
QA Plan
-------

Print retired tags into slack/terminal on audit

---

lib/sport_ngin_aws_auditor/cache_instance.rb
lib/sport_ngin_aws_auditor/ec2_instance.rb
lib/sport_ngin_aws_auditor/instance.rb
lib/sport_ngin_aws_auditor/instance_helper.rb
lib/sport_ngin_aws_auditor/rds_instance.rb
lib/sport_ngin_aws_auditor/recently_retired_tag.rb
lib/sport_ngin_aws_auditor/scripts/audit.rb
spec/sport_ngin_aws_auditor/ec2_instance_spec.rb
spec/sport_ngin_aws_auditor/instance_spec.rb
spec/sport_ngin_aws_auditor/rds_instance_spec.rb
spec/sport_ngin_aws_auditor/recently_retired_tag_spec.rb
sport_ngin_aws_auditor.gemspec

In the output of the expired EC2 tags:
* write name of the EC2 instance
* write value of the no-reserved-instance-reason (if exists)
In the output of the blue no-reserved-instance instances:
* write value of the no-reserved-instance-reason (if exists)
* the date on when to re-evaluate (the value of the tag)
Clarify whether the instances are unused, missing, or tagged as well as showing with colors.
```
Red: Unused RI
Yellow: Missing RI
Blue: No RI Yet
```
Deploy Plan
-----------
* merge into staging
* `op tag-release`
Rollback Plan
-------------
URLs
----
http://stackoverflow.com/questions/1489183/colorized-ruby-output
QA Plan
-------

Clarifying printout of audit command

---

lib/sport_ngin_aws_auditor/ec2_instance.rb
lib/sport_ngin_aws_auditor/instance_helper.rb

Fix bug where the counts of RIs and instances were off and the hashes weren't updating counts correctly.
Deploy Plan
-----------
* merge into staging
Rollback Plan
-------------
URLs
----
QA Plan
-------

Fixing bugs so that counts are accurate again

---

lib/sport_ngin_aws_auditor/instance_helper.rb
lib/sport_ngin_aws_auditor/scripts/audit.rb

There should only be one tagged output per line, even if the description of the instance is the same. The printed tagged outputs should include the name of the instance and the description, instead of just the description. The list of Unused RIs should take tagged outputs into account, so show that an RI is covering a tagged output. The list of recently expired tags should output tags that expire today.
Deploy Plan
-----------
Rollback Plan
-------------
URLs
----
QA Plan
-------

Fixing bugs with outputs and counts

---

.travis.yml
lib/sport_ngin_aws_auditor/commands/audit.rb
lib/sport_ngin_aws_auditor/notify_slack.rb
lib/sport_ngin_aws_auditor/scripts/audit.rb
spec/sport_ngin_aws_auditor/notify_slack_spec.rb
sport_ngin_aws_auditor.gemspec

Give the option for passing config information in as a flag, instead of as a file.
Deploy Plan
-----------
Rollback Plan
-------------
URLs
----
QA Plan
-------

Add the ability to pass config data in as a flag

---

lib/sport_ngin_aws_auditor/audit_data.rb
lib/sport_ngin_aws_auditor/cache_instance.rb
lib/sport_ngin_aws_auditor/commands/audit.rb
lib/sport_ngin_aws_auditor/ec2_instance.rb
lib/sport_ngin_aws_auditor/instance.rb
lib/sport_ngin_aws_auditor/instance_helper.rb
lib/sport_ngin_aws_auditor/rds_instance.rb
lib/sport_ngin_aws_auditor/scripts/audit.rb
spec/sport_ngin_aws_auditor/audit_data_spec.rb
spec/sport_ngin_aws_auditor/ec2_instance_spec.rb
spec/sport_ngin_aws_auditor/instance_helper_spec.rb
spec/sport_ngin_aws_auditor/instance_spec.rb

This will take reserved EC2Instances into account if they are region-based (if they have no zone-specific). It first does the original math and counting for zone-specific instances and RIs, and then last factors in if they are region-based. It also offers a couple of different printing techniques for whether we are using region-based RIs or not. If a RI is region-based, then it will only print the region (not the zone). If a RI is zone-specific, then it will continue to print the zone. For Missing RI and Tagged RI outputs, then there is a new option (`-z` or `--zone_output`) that will tell the program to print the zones to the outputs, otherwise it will just print regions.
\* To run this, the version of aws-sdk must be at 2.6.6 or higher.
Does Platform Operations need to know anything …

Handling region-based RIs

---

lib/sport_ngin_aws_auditor/ec2_instance.rb
lib/sport_ngin_aws_auditor/instance_helper.rb
spec/sport_ngin_aws_auditor/instance_helper_spec.rb

When the auditor is run multiple times close together the auditor caches the data for the instances and RIs. And the method `apply_region_ris` was editing the count of each RI (which was what I had originally intended). But a side effect is that when the counts are edited, the cached versions are also edited, so following runs of the auditor causes the RI counts to start off as incorrect.
This PR adds another little part of the ec2instance object: `mutable_count` that we can actively change in `apply_region_ris` without affecting the original count number of the cached RIs.
Deploy Plan
-----------
- checkout master
- `op accept-pull 25`
- `soyuz deploy`
Rollback Plan
-------------
* To roll back this change, revert the merge with: `git revert …

Caching should not affect RI counts between runs

---

lib/sport_ngin_aws_auditor/audit_data.rb
lib/sport_ngin_aws_auditor/commands/audit.rb
lib/sport_ngin_aws_auditor/instance.rb
lib/sport_ngin_aws_auditor/instance_helper.rb
lib/sport_ngin_aws_auditor/scripts/audit.rb
spec/sport_ngin_aws_auditor/audit_data_spec.rb
spec/sport_ngin_aws_auditor/instance_helper_spec.rb

Automatically ignore certain running instances if they have the words `kitchen` or `auto` in their title. This should print them in blue (like tagged instances), but will say `IGNORED` instead.
Deploy Plan
-----------
- checkout master
- `op accept-pull 26`
- `soyuz deploy`
Rollback Plan
-------------
URLs
----
QA Plan
-------

Automatically ignore instances based on a regex string

---

lib/sport_ngin_aws_auditor/instance_helper.rb
lib/sport_ngin_aws_auditor/scripts/audit.rb

Fix bug where the auditor will break if `instance.name` is nil, and a bug where the auditor will error if no regex patterns are passed in.
Deploy Plan
-----------
Rollback Plan
-------------
URLs
----
QA Plan
-------
The two errors I've seen here are one on line 30 of `lib/sport_ngin_aws_auditor/scripts/audit.rb` (undefined method 'each' for nil) and one on line 61 of `lib/sport_ngin_aws_auditor/instance_helper.rb`(no implicit conversion of nil into string)

Must merge this PR in to run the audit command correctly

---

lib/sport_ngin_aws_auditor/cache_instance.rb
lib/sport_ngin_aws_auditor/ec2_instance.rb
lib/sport_ngin_aws_auditor/instance_helper.rb
lib/sport_ngin_aws_auditor/rds_instance.rb
lib/sport_ngin_aws_auditor/scripts/audit.rb

When the auditor was originally made, we implemented some caching of the instances and reserved instances, so that tons of API calls wouldn't be made over and over again when no changes were in place. However, now we want the auditor to gather fresh data every time we run the auditor, so we don't want any caching in place. This may slow down the results of some of the runs of the auditor, but we prefer that over the caching.
Deploy Plan
-----------
* checkout master
* `op accept-pull 29`
Rollback Plan
-------------
URLs
----
QA Plan
-------

We actually do not want to cache the counts of instances and reserved instances between multiple runs

---

.travis.yml
bin/sport-ngin-aws-auditor
lib/sport_ngin_aws_auditor/audit_data.rb
lib/sport_ngin_aws_auditor/aws.rb
lib/sport_ngin_aws_auditor/cache_instance.rb
lib/sport_ngin_aws_auditor/convenience_wrappers.rb
lib/sport_ngin_aws_auditor/ec2_instance.rb
lib/sport_ngin_aws_auditor/instance_helper.rb
lib/sport_ngin_aws_auditor/rds_instance.rb
lib/sport_ngin_aws_auditor/scripts/audit.rb
lib/sport_ngin_aws_auditor/scripts/inspect.rb
spec/sport_ngin_aws_auditor/audit_data_spec.rb
spec/sport_ngin_aws_auditor/aws_spec.rb
spec/sport_ngin_aws_auditor/cache_instance_spec.rb
spec/sport_ngin_aws_auditor/ec2_instance_spec.rb
spec/sport_ngin_aws_auditor/rds_instance_spec.rb
sport_ngin_aws_auditor.gemspec

We want to be able to audit multiple accounts in AWS (in different regions and under different names) with only needing to generate one secret access key and key id. Moreover, right now whatever server is running the audit is only capable of auditing that region in that account. Therefore, we want to be able to give that single account all of the permissions and access to audit other accounts. Therefore, we'll use AWS roles to give our main account access to others and we'll make multiple clients, one for each region we are auditing. The link about cross account roles is in the URLs section.
This PR will run all U.S. regions by default, or a list of specified regions. It also revamped the printing of both the terminal outputs and the Slack …

Adding abilities to audit cross account

---

lib/sport_ngin_aws_auditor/instance.rb
lib/sport_ngin_aws_auditor/scripts/audit.rb

When there are multiple lines with the same types of instances, as shown in this image, they should be combined into one single line for the specific region.
So here, there should be one line showing that we need 6 c3.4xlarge reserved instances, instead of them being separated by zone (which isn't even showing up when we use the auditor). However, because we want the auditor to support zone-based, whether they're combined should depend on whether the auditor is being run as region-based or zone-based.
Deploy Plan
-----------
* `git checkout master`
* `git pull`
* `op accept-pull 27`
Rollback Plan
-------------
URLs
----
> …

Concat all of the similar values into one value right before printing

---

lib/sport_ngin_aws_auditor/rds_instance.rb
lib/sport_ngin_aws_auditor/scripts/audit.rb
spec/sport_ngin_aws_auditor/rds_instance_spec.rb

Like in `cache_instance.rb` and `ec2_instance.rb`, we need to define what `.availability_zone` should be for each object. The documentation (linked below) says what each RDS instance has, so we need to define those in ours so that when we call it on line 100 of `audit.rb`, the objects are ready.
Deploy Plan
-----------
Rollback Plan
-------------
URLs
----
http://docs.aws.amazon.com/sdkforruby/api/Aws/RDS/Client.html
QA Plan
-------

Define availability zone as attribute for RDS object to avoid errors

---

lib/sport_ngin_aws_auditor/aws.rb
spec/sport_ngin_aws_auditor/aws_spec.rb

What
Change assume roles and mfa to use shared credentials file or aws instance profile for STS client.
Why
It was broken when ran on non-AWS server instance.
QA Plan
-------

Patch MFA and assume roles on non-AWS host

---

lib/sport_ngin_aws_auditor/audit_data.rb
lib/sport_ngin_aws_auditor/instance_helper.rb
lib/sport_ngin_aws_auditor/rds_instance.rb
lib/sport_ngin_aws_auditor/scripts/audit.rb
spec/sport_ngin_aws_auditor/instance_helper_spec.rb

What
Match RDS platforms correctly. Match EC2 classic platforms more accurately. Show more information when printing out tagged and ignored instances.
Deploy Plan
-----------
Merge in and make a new version. Push to rubygems.
Rollback Plan
-------------
URLs
----
QA Plan
-------

Compare platforms of RDS and EC2 instances correctly

---

lib/sport_ngin_aws_auditor/rds_instance.rb
spec/sport_ngin_aws_auditor/rds_instance_spec.rb
sport_ngin_aws_auditor.gemspec

What
When running the auditor on a region that is more than 9 characters ("us-east-1" is 9, but "ap-southeast-1" is not), it breaks because previously the auditor was looking for exactly 9 characters when finding the region.
Deploy Plan
-----------
Rollback Plan
-------------
URLs
----
QA Plan
-------

Fix bug where using the auditor with a region more than 9 characters doesn't work
